binary:
	gcc -c -fPIC -O2 color.c
	gcc -c -fPIC -O2 anscii.c
crosscompile:
	x86_64-elf-gcc -c -fPIC -O2 color.c
	x86_64-elf-gcc -c -fPIC -O2 anscii.c
linux:
	gcc -c -fPIC -O2 color.c
	gcc -c -fPIC -O2 anscii.c
mac:
	clang -c -fPIC -O2 color.c
	clang -c -fPIC -O2 anscii.c
win:
	gcc -c -O2 color.c
	gcc -c -O2 anscii.c