linux:
	gcc -c -fPIC -O2 master.c
	gcc -c -fPIC -O2 fat.c
	gcc -c -fPIC -O2 ntfs.c
	gcc -c -fPIC -O2 ext.c
cross:
	x86_64-elf-gcc -c -fPIC -O2 master.c
	x86_64-elf-gcc -c -fPIC -O2 fat.c
	x86_64-elf-gcc -c -fPIC -O2 ntfs.c
	x86_64-elf-gcc -c -fPIC -O2 ext.c