binary:
	gcc -c -fPIC -O2 2048.c
	gcc -c -fPIC -O2 anscii.c
crosscompile:
	x86_64-elf-gcc -c -fPIC -O2 2048.c
	x86_64-elf-gcc -c -fPIC -O2 anscii.c
linux:
	gcc -c 2048.c
	gcc -c anscii.c
mac:
	clang -c 2048.c
	clang -c anscii.c
win:
	gcc -c 2048.c
	gcc -c anscii.c