binary:
	gcc -c -fPIC -O2 ooxx.c
	gcc -c -fPIC -O2 anscii.c
	gcc -c -fPIC -O2 math.c
crosscompile:
	x86_64-elf-gcc -c -fPIC -O2 ooxx.c
	x86_64-elf-gcc -c -fPIC -O2 anscii.c
	x86_64-elf-gcc -c -fPIC -O2 math.c
linux:
	gcc -c -O2 ooxx.c
	gcc -c -O2 anscii.c
	gcc -c -O2 math.c
mac:
	clang -c -O2 ooxx.c
	clang -c -O2 anscii.c
	clang -c -O2 math.c
win:
	gcc -c -O2 ooxx.c
	gcc -c -O2 anscii.c
	gcc -c -O2 math.c
