.PHONY:bare
bare:
	gcc -c -fPIC -O2 bare/start.c
	gcc -c -fPIC -O2 bare/print.c
	gcc -c -fPIC -O2 bare/malloc.c
.PHONY:cross
cross:
.PHONY:linux
linux:
	gcc -c -fPIC -O2 linux/sdl.c
	gcc -c -fPIC -O2 linux/malloc.c
