#!/bin/sh
dir=`dirname $0`
echo "本脚本的位置:$dir"
core=$dir/../../core
echo "代码位置:$core"


sudo losetup /dev/loop2 $dir/live.img			#loop设备
sudo partprobe /dev/loop2
sudo mkdir -p /mnt/tempmountpointforlive		#临时挂载点
sudo mount /dev/loop2p1 /mnt/tempmountpointforlive	#挂载fat32
