#!/bin/sh
dir=`dirname $0`
echo "本脚本的位置:$dir"
core=$dir/../../core
echo "代码位置:$core"


dd if=/dev/zero of=$dir/64m.img bs=512 count=131072
dd if=$core/core.bin of=$dir/64m.img conv=notrunc
echo "搞定，现在可以运行qemu"
