linux:
	gcc -c -fPIC -O2 print.c
	gcc -c -fPIC -O2 remember.c
	gcc -c -fPIC -O2 else.c
cross:
	x86_64-elf-gcc -c -fPIC -O2 print.c
	x86_64-elf-gcc -c -fPIC -O2 remember.c
	x86_64-elf-gcc -c -fPIC -O2 else.c