all:
	rm -rf demo
	mkdir demo
	make -s -C easiest
	cp easiest/easiest demo/
	make -s -C jpeg
	cp jpeg/jpeg demo/
	make -s -C multitask
	cp multitask/multi demo/
	make -s -C zimo
	cp zimo/zimo demo/
	make -s -C 2048
	cp 2048/2048 demo/
	make -s -C tetris
	cp tetris/tetris demo/
	make -s -C 3d
	cp 3d/3d demo/
	make -s -C agnesi
	cp agnesi/agnesi demo/
	make -s -C brick
	cp brick/brick demo/
	make -s -C flappybird
	cp flappybird/bird demo/
	make -s -C g
	cp g/g demo/
	make -s -C snake
	cp snake/snake demo/
	make -s -C taiji
	cp taiji/taiji demo/
	make -s -C tetris
	cp tetris/tetris demo/
	make -s -C win8
	cp win8/win8 demo/
	make -s -C xiangqi
	cp xiangqi/xiangqi demo/
	make -s -C clock
	cp clock/clock demo/
	make -s -C math
	cp math/math demo/
	make -s -C btree
	cp btree/btree demo/
	make -s -C sketchpad
	cp sketchpad/sketchpad demo/
	make -s -C mandelbrot
	cp mandelbrot/mandelbrot demo/
clean:
	rm -rf demo
	make clean -s -C easiest
	make clean -s -C jpeg
	make clean -s -C multitask
	make clean -s -C zimo
	make clean -s -C 2048
	make clean -s -C tetris
	make clean -s -C 3d
	make clean -s -C agnesi
	make clean -s -C brick
	make clean -s -C flappybird
	make clean -s -C g
	make clean -s -C snake
	make clean -s -C taiji
	make clean -s -C tetris
	make clean -s -C win8
	make clean -s -C xiangqi
	make clean -s -C clock
	make clean -s -C math
	make clean -s -C sketchpad
	make clean -s -C btree
	make clean -s -C mandelbrot
