clean:
	rm -f demo
	make clean -s -C easiest
	make clean -s -C jpeg
	make clean -s -C multitask
	make clean -s -C zimo
	make clean -s -C 2048
	make clean -s -C tetris
	make clean -s -C 3d
	make clean -s -C agnesi
	make clean -s -C brick
	make clean -s -C flappybird
	make clean -s -C g
	make clean -s -C snake
	make clean -s -C taiji
	make clean -s -C tetris
	make clean -s -C win8
	make clean -s -C xiangqi
	make clean -s -C clock
