linux:
	gcc -c -fPIC -O2 identify.c
	gcc -c -fPIC -O2 read.c
	gcc -c -fPIC -O2 journal.c
cross:
	x86_64-elf-gcc -c -fPIC -O2 identify.c
	x86_64-elf-gcc -c -fPIC -O2 read.c
	x86_64-elf-gcc -c -fPIC -O2 journal.c
